"""
Standard Catalog of 2-Level Fractional Factorial Designs (Box-Hunter / Montgomery).
"""

from __future__ import annotations

import warnings
from typing import Any, Dict, List, Optional


CATALOG_DESIGNS: Dict[str, Dict[str, Any]] = {
    "2(3-1)III": {
        "plan_id": "2(3-1)III",
        "factors": "ABC",
        "num_factors": 3,
        "fraction": 1,
        "resolution": 3,
        "runs": 4,
        "base_factors": ["A", "B"],
        "generators": ["C=AB"],
        "identity": "I = ABC",
    },
    "2(4-1)IV": {
        "plan_id": "2(4-1)IV",
        "factors": "ABCD",
        "num_factors": 4,
        "fraction": 1,
        "resolution": 4,
        "runs": 8,
        "base_factors": ["A", "B", "C"],
        "generators": ["D=ABC"],
        "identity": "I = ABCD",
    },
    "2(5-1)V": {
        "plan_id": "2(5-1)V",
        "factors": "ABCDE",
        "num_factors": 5,
        "fraction": 1,
        "resolution": 5,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": ["E=ABCD"],
        "identity": "I = ABCDE",
    },
    "2(5-2)III": {
        "plan_id": "2(5-2)III",
        "factors": "ABCDE",
        "num_factors": 5,
        "fraction": 2,
        "resolution": 3,
        "runs": 8,
        "base_factors": ["A", "B", "C"],
        "generators": ["D=AB", "E=AC"],
        "identity": "I = ABD = ACE = BCDE",
    },
    "2(6-1)VI": {
        "plan_id": "2(6-1)VI",
        "factors": "ABCDEF",
        "num_factors": 6,
        "fraction": 1,
        "resolution": 6,
        "runs": 32,
        "base_factors": ["A", "B", "C", "D", "E"],
        "generators": ["F=ABCDE"],
        "identity": "I = ABCDEF",
    },
    "2(6-2)IV": {
        "plan_id": "2(6-2)IV",
        "factors": "ABCDEF",
        "num_factors": 6,
        "fraction": 2,
        "resolution": 4,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": ["E=ABC", "F=BCD"],
        "identity": "I = ABCE = BCDF = ADEF",
    },
    "2(6-3)III": {
        "plan_id": "2(6-3)III",
        "factors": "ABCDEF",
        "num_factors": 6,
        "fraction": 3,
        "resolution": 3,
        "runs": 8,
        "base_factors": ["A", "B", "C"],
        "generators": ["D=AB", "E=AC", "F=BC"],
        "identity": "I = ABD = ACE = BCF = BCDE = ACDF = ABEF = DEF",
    },
    "2(7-1)VII": {
        "plan_id": "2(7-1)VII",
        "factors": "ABCDEFG",
        "num_factors": 7,
        "fraction": 1,
        "resolution": 7,
        "runs": 64,
        "base_factors": ["A", "B", "C", "D", "E", "F"],
        "generators": ["G=ABCDEF"],
        "identity": "I = ABCDEFG",
    },
    "2(7-2)IV": {
        "plan_id": "2(7-2)IV",
        "factors": "ABCDEFG",
        "num_factors": 7,
        "fraction": 2,
        "resolution": 4,
        "runs": 32,
        "base_factors": ["A", "B", "C", "D", "E"],
        "generators": ["F=ABCD", "G=ABDE"],
        "identity": "I = ABCDF = ABDEG = CEFG",
    },
    "2(7-3)IV": {
        "plan_id": "2(7-3)IV",
        "factors": "ABCDEFG",
        "num_factors": 7,
        "fraction": 3,
        "resolution": 4,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": ["E=ABC", "F=BCD", "G=ACD"],
        "identity": "I = ABCE = BCDF = ACDG = ADEF = BDEG = ABFG = CEFG",
    },
    "2(7-4)III": {
        "plan_id": "2(7-4)III",
        "factors": "ABCDEFG",
        "num_factors": 7,
        "fraction": 4,
        "resolution": 3,
        "runs": 8,
        "base_factors": ["A", "B", "C"],
        "generators": ["D=AB", "E=AC", "F=BC", "G=ABC"],
        "identity": "I = ABD = ACE = BCF = ABCG = ...",
    },
    "2(8-2)V": {
        "plan_id": "2(8-2)V",
        "factors": "ABCDEFGH",
        "num_factors": 8,
        "fraction": 2,
        "resolution": 5,
        "runs": 64,
        "base_factors": ["A", "B", "C", "D", "E", "F"],
        "generators": ["G=ABCD", "H=ABEF"],
        "identity": "I = ABCDG = ABEFH = CDEFGH",
    },
    "2(8-3)IV": {
        "plan_id": "2(8-3)IV",
        "factors": "ABCDEFGH",
        "num_factors": 8,
        "fraction": 3,
        "resolution": 4,
        "runs": 32,
        "base_factors": ["A", "B", "C", "D", "E"],
        "generators": ["F=BCDE", "G=ACDE", "H=ABDE"],
        "identity": "I = BCDEF = ACDEG = ABDEH = ...",
    },
    "2(8-4)IV": {
        "plan_id": "2(8-4)IV",
        "factors": "ABCDEFGH",
        "num_factors": 8,
        "fraction": 4,
        "resolution": 4,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": ["E=BCD", "F=ACD", "G=ABD", "H=ABC"],
        "identity": "I = BCDE = ACDF = ABDG = ABCH = ...",
    },
    "2(9-2)VI": {
        "plan_id": "2(9-2)VI",
        "factors": "ABCDEFGHJ",
        "num_factors": 9,
        "fraction": 2,
        "resolution": 6,
        "runs": 128,
        "base_factors": ["A", "B", "C", "D", "E", "F", "G"],
        "generators": ["H=ABCDE", "J=ACDFG"],
        "identity": "I = ABCDEH = ACDFGJ = BEFGHJ",
    },
    "2(9-3)IV": {
        "plan_id": "2(9-3)IV",
        "factors": "ABCDEFGHJ",
        "num_factors": 9,
        "fraction": 3,
        "resolution": 4,
        "runs": 64,
        "base_factors": ["A", "B", "C", "D", "E", "F"],
        "generators": ["G=ABCD", "H=ACEF", "J=CDEF"],
        "identity": "I = ABCDG = ACEFH = CDEFJ = ...",
    },
    "2(9-4)IV": {
        "plan_id": "2(9-4)IV",
        "factors": "ABCDEFGHJ",
        "num_factors": 9,
        "fraction": 4,
        "resolution": 4,
        "runs": 32,
        "base_factors": ["A", "B", "C", "D", "E"],
        "generators": ["F=BCDE", "G=ACDE", "H=ABDE", "J=ABCD"],
        "identity": "I = BCDEF = ACDEG = ABDEH = ABCDJ = ...",
    },
    "2(9-5)III": {
        "plan_id": "2(9-5)III",
        "factors": "ABCDEFGHJ",
        "num_factors": 9,
        "fraction": 5,
        "resolution": 3,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": ["E=ABC", "F=BCD", "G=ACD", "H=ABD", "J=ABCD"],
        "identity": "I = ABCE = BCDF = ACDG = ABDH = ABCDJ = ...",
    },
    "2(10-3)V": {
        "plan_id": "2(10-3)V",
        "factors": "ABCDEFGHJK",
        "num_factors": 10,
        "fraction": 3,
        "resolution": 5,
        "runs": 128,
        "base_factors": ["A", "B", "C", "D", "E", "F", "G"],
        "generators": ["H=ABCD", "J=ABEF", "K=ACEG"],
        "identity": "I = ABCDH = ABEFJ = ACEGK = CDEFHJ = BDEGHK = BCFGJK = ADFGHJK",
    },
    "2(10-4)IV": {
        "plan_id": "2(10-4)IV",
        "factors": "ABCDEFGHJK",
        "num_factors": 10,
        "fraction": 4,
        "resolution": 4,
        "runs": 64,
        "base_factors": ["A", "B", "C", "D", "E", "F"],
        "generators": ["G=BCDF", "H=ACDF", "J=ABDE", "K=ABCE"],
        "identity": "I = BCDFG = ACDFH = ABDEJ = ABCEK = ...",
    },
    "2(10-5)IV": {
        "plan_id": "2(10-5)IV",
        "factors": "ABCDEFGHJK",
        "num_factors": 10,
        "fraction": 5,
        "resolution": 4,
        "runs": 32,
        "base_factors": ["A", "B", "C", "D", "E"],
        "generators": ["F=ABCD", "G=ABCE", "H=ABDE", "J=ACDE", "K=BCDE"],
        "identity": "I = ABCDF = ABCEG = ABDEH = ACDEJ = BCDEK = ...",
    },
    "2(10-6)III": {
        "plan_id": "2(10-6)III",
        "factors": "ABCDEFGHJK",
        "num_factors": 10,
        "fraction": 6,
        "resolution": 3,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": ["E=ABC", "F=BCD", "G=ACD", "H=ABD", "J=ABCD", "K=AB"],
        "identity": "I = ABCE = BCDF = ACDG = ABDH = ABCDJ = ABK = ...",
    },
    "2(11-4)V": {
        "plan_id": "2(11-4)V",
        "factors": "ABCDEFGHJKL",
        "num_factors": 11,
        "fraction": 4,
        "resolution": 5,
        "runs": 128,
        "base_factors": ["A", "B", "C", "D", "E", "F", "G"],
        "generators": ["H=ABCG", "J=BCDE", "K=ACDF", "L=ABCDEFG"],
        "identity": "I = ABCGH = BCDEJ = ACDFK = ABCDEFGL = ...",
    },
    "2(11-5)IV": {
        "plan_id": "2(11-5)IV",
        "factors": "ABCDEFGHJKL",
        "num_factors": 11,
        "fraction": 5,
        "resolution": 4,
        "runs": 64,
        "base_factors": ["A", "B", "C", "D", "E", "F"],
        "generators": ["G=CDE", "H=ABCD", "J=ABF", "K=BDEF", "L=ADEF"],
        "identity": "I = CDEG = ABCDH = ABFJ = BDEFK = ADEFL = ...",
    },
    "2(11-6)IV": {
        "plan_id": "2(11-6)IV",
        "factors": "ABCDEFGHJKL",
        "num_factors": 11,
        "fraction": 6,
        "resolution": 4,
        "runs": 32,
        "base_factors": ["A", "B", "C", "D", "E"],
        "generators": ["F=ABC", "G=BCD", "H=CDE", "J=ACD", "K=ADE", "L=BDE"],
        "identity": "I = ABCF = BCDG = CDEH = ACDJ = ADEK = BDEL = ...",
    },
    "2(11-7)III": {
        "plan_id": "2(11-7)III",
        "factors": "ABCDEFGHJKL",
        "num_factors": 11,
        "fraction": 7,
        "resolution": 3,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": ["E=ABC", "F=BCD", "G=ACD", "H=ABD", "J=ABCD", "K=AB", "L=AC"],
        "identity": "I = ABCE = BCDF = ACDG = ABDH = ABCDJ = ABK = ACL = ...",
    },
    "2(15-11)III": {
        "plan_id": "2(15-11)III",
        "factors": "ABCDEFGHJKLMNOP",
        "num_factors": 15,
        "fraction": 11,
        "resolution": 3,
        "runs": 16,
        "base_factors": ["A", "B", "C", "D"],
        "generators": [
            "E=AB", "F=AC", "G=AD", "H=BC", "J=BD", "K=CD",
            "L=ABC", "M=ABD", "N=ACD", "O=BCD", "P=ABCD"
        ],
        "identity": "I = ABE = ACF = ADG = BCH = BDJ = CDK = ABCL = ABDM = ACDN = BCDO = ABCDP = ...",
    },
}


def get_catalog_entry(plan_id: str) -> Optional[Dict[str, Any]]:
    """Retrieve catalog metadata for a specific plan ID."""
    norm_id = plan_id.replace("^", "").strip()
    if norm_id == "2(11-4)VI":
        warnings.warn(
            "Plan ID '2(11-4)VI' is deprecated and has been corrected to '2(11-4)V' (true Resolution V).",
            DeprecationWarning,
            stacklevel=2,
        )
        return CATALOG_DESIGNS.get("2(11-4)V")
    return CATALOG_DESIGNS.get(norm_id)


def list_available_plans(num_factors: Optional[int] = None) -> List[Dict[str, Any]]:
    """List all available catalog designs, optionally filtered by number of factors."""
    plans = list(CATALOG_DESIGNS.values())
    if num_factors is not None:
        plans = [p for p in plans if p["num_factors"] == num_factors]
    return plans
